
export const appConstants = {
    GET_CITY_REQUEST: "GET_CITY_REQUEST",
    GET_CITY_SUCCESS: "GET_CITY_SUCCESS",
    GET_CITY_FAILURE: "GET_CITY_FAILURE",
    ADD_CITY_REQUEST: "ADD_CITY_REQUEST",
    ADD_CITY_SUCCESS: "ADD_CITY_SUCCESS",
    ADD_CITY_FAILURE: "ADD_CITY_FAILURE",
    ADD_CITY: "ADD_CITY",
    REMOVE_CITY_ITEM: "REMOVE_CITY_ITEM",
    TOGGLE_CITY_STATUS: "TOGGLE_CITY_STATUS",
    GET_COUNTRY_REQUEST: "GET_COUNTRY_REQUEST",
    GET_COUNTRY_SUCCESS: "GET_COUNTRY_SUCCESS",
    GET_COUNTRY_FAILURE: "GET_COUNTRY_FAILURE",
    ADD_COUNTRY_REQUEST: "ADD_COUNTRY_REQUEST",
    ADD_COUNTRY_SUCCESS: "ADD_COUNTRY_SUCCESS",
    ADD_COUNTRY_FAILURE: "ADD_COUNTRY_FAILURE",
    ADD_COUNTRY: "ADD_COUNTRY",
    REMOVE_COUNTRY_ITEM: "REMOVE_COUNTRY_ITEM",
    TOGGLE_COUNTRY_STATUS: "TOGGLE_COUNTRY_STATUS"
};